server:
  port: 8582
  servlet:
    context-path: /community


spring:
  #  数据库数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: (3.1415926Pai)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  
  #模板引擎的配置
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
    check-template-location: true
  
  #  邮箱发送配置
  mail:
    port: 465
    host: smtp.sina.com
    username: sincos99248@sina.com
    password: 4bf7ba703dbbbb5a
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 3000
          ssl:
            enable: true
  redis:
    database: 11
    host: localhost
    port: 6379
  # kafka配置
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  #      Elasticsearch配置
  data:
    elasticsearch:
      cluster:
        - name=ahg
        - nodes=127.0.0.1:9300




#mybatis配置
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.ahg.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

#logging:
#  level.com.ahg.community: debug
#  file: d:/workspace/data/ahg/community.log

#自定义配置
community:
  path:
    domain: http://localhost:8582
    upload: d:/work/data/upload


